
spring:
  application:
    name: microservice
  sleuth:
    sampler:
      probability: 1.0

search:
  host: http://opendata-ajuntament.barcelona.cat/data/api/3/action/package_search
  default:
    lang: ca

---
spring:
  profiles: default

server:
    port: 9999

---
spring:
  profiles: test

server:
    port: 8080
---
spring:
    profiles: production
server:
    port: 8080