spring:
  profiles: default

server:
    port: 9999
search:
  host: http://opendata-ajuntament.barcelona.cat/data/api/3/action/package_search

---
spring:
  profiles: test

server:
    port: 8080
---
spring:
    profiles: production
server:
    port: 8080